name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
  push: # Runs on every push to the main branch
    branches:
      - main

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: True
          SHOW_LANGUAGE: True
          SHOW_OS: True
          TIME_RANGE: all_time
          CODE_LANG: go
          SHOW_TIME: True
          SHOW_TOTAL: True
